const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const FETCH_TODO = "FETCH_TODO";
const COMPLETE_TODO = "COMPLETE_TODO";
const STORE_TODOS_IN_STATE = "STORE_TODOS_IN_STATE";

export {
  ADD_TODO,
  COMPLETE_TODO,
  DELETE_TODO,
  FETCH_TODO,
  STORE_TODOS_IN_STATE,
};
